2014-10-01 14:18:52,762 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-10-01 14:18:52,800 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (그런 파일이나 디렉터리가 없습니다)
2014-10-01 14:18:54,089 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-10-01 14:18:54,551 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-10-01 14:18:54,557 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-10-01 14:18:54,575 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-10-01 14:18:54,575 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-10-01 14:18:54,841 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-10-01 14:18:56,584 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xeb\xb6\x80\xec\xa0\x81\xec\xa0\x88\xed\x95\x9c \xec\x9d\xb8\xec\x88\x98 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-10-01 14:18:56,588 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xeb\xb6\x80\xec\xa0\x81\xec\xa0\x88\xed\x95\x9c \xec\x9d\xb8\xec\x88\x98 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-10-01 14:19:06,835 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-10-01 14:19:08,534 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (그런 파일이나 디렉터리가 없습니다)
2014-10-01 14:19:10,801 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
